trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  api_key: $(API_KEY)

stages:
  - stage: FunctionalTests
    jobs:
      - job: RunFunctionalTests
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              echo "Running Smoke Tests..."
              mvn clean test -Psmoke
            displayName: 'Run Smoke Tests'

          - script: |
              echo "Running Regression Tests..."
              mvn clean test -Pregression
            displayName: 'Run Regression Tests'

          - script: |
              echo "Running E2E Tests..."
              mvn clean test -Pe2e
            displayName: 'Run E2E Tests'

          - script: |
              echo "All functional tests passed successfully."
            displayName: 'Functional Tests Passed'

  - stage: LoadTest
    dependsOn: FunctionalTests
    condition: succeeded()
    jobs:
      - job: RunLoadTests
        steps:
          - script: |
              echo "Running Load Tests..."
              k6 run load-test.js
            displayName: 'Run Load Tests'
